[package]
name = "test_infra"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# zksync_multivm = { git = "https://github.com/matter-labs/zksync-era.git", rev = "8a3725ac18fbb83d4d191d73a144418f6f02474f" }
# zksync_types = { git = "https://github.com/matter-labs/zksync-era.git", rev = "8a3725ac18fbb83d4d191d73a144418f6f02474f" }
# zksync_contracts = { git = "https://github.com/matter-labs/zksync-era.git", rev = "8a3725ac18fbb83d4d191d73a144418f6f02474f" }
# zksync_utils = { git = "https://github.com/matter-labs/zksync-era.git", rev = "8a3725ac18fbb83d4d191d73a144418f6f02474f" }
# zksync_state = { git = "https://github.com/matter-labs/zksync-era.git", rev = "8a3725ac18fbb83d4d191d73a144418f6f02474f" }
# zksync_vlog = { git = "https://github.com/matter-labs/zksync-era.git", rev = "8a3725ac18fbb83d4d191d73a144418f6f02474f" }

zksync_multivm = { path = "../../../../core/lib/multivm" }
zksync_types = { path = "../../../../core/lib/types" }
zksync_contracts = { path = "../../../../core/lib/contracts" }
zksync_utils = { path = "../../../../core/lib/utils" }
zksync_state = { path = "../../../../core/lib/state" }
zksync_vlog = { path = "../../../../core/lib/vlog" }

colored = "2.0"
hex = "0.4"
once_cell = "1.7"
tracing = { version = "0.1.26", features = ["log"] }
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter", "time", "json"] }
serde_json = "1.0.67"
serde = { version = "1.0", features = ["derive"] }

[patch.crates-io]
vise = { git = "https://github.com/matter-labs/vise.git", rev = "51669f42f60c50b3a521662a4ecd71212a303299" }
