name: Install l1-contract dependencies
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install foundry-zksync
      uses: dutterbutter/foundry-zksync-toolchain@5b0459c3701903f1913b8b2558a22bf49138e495 # v1.0.0
      with:
        version: nightly-27360d4c8d12beddbb730dae07ad33a206b38f4b

    - name: Show forge version
      shell: bash
      run: forge --version

    - name: Cache yarn packages
      uses: actions/setup-node@v4
      with:
        cache: yarn

    - name: Install yarn packages
      shell: bash
      run: yarn

    - name: Build artifacts
      shell: bash
      run: |
        # creates JSON files needed for `yarn l1 test:zkfoundry`
        yarn sc build:foundry
        cd l1-contracts
        # creates `l1-contracts/script-out/diamond-selectors.toml` which is needed for `l1-contracts/deploy-scripts/DeployUtils.s.sol`
        yarn test:zkfoundry
