name: Invariant Tests

on:
  schedule:
    - cron: "00 01 * * *"
  workflow_dispatch:
  pull_request: # TODO: remove this trigger before merging because for some time the workflow should run only on schedule until the invariant tests are stable enough to be run on every pull request

permissions: read-all

jobs:
  l1-context:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        uses: matter-labs/era-contracts/.github/actions/l1-contracts-setup@nikita/invariant-tests # TODO: replace with `main` before merging

      - name: Run tests
        run: |
          cd l1-contracts
          # TODO: uncomment this before merging: export FOUNDRY_PROFILE=invariant_tests_l1context_ci
          yarn test:invariant:l1-context
  
  l2-context:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        uses: matter-labs/era-contracts/.github/actions/l1-contracts-setup@nikita/invariant-tests # TODO: replace with `main` before merging

      - name: Run tests
        run: |
          cd l1-contracts
          # TODO: uncomment this before merging: export FOUNDRY_PROFILE=invariant_tests_l2context_ci
          yarn test:invariant:l2-context
