name: Invariant Tests

on:
  schedule:
    - cron: "00 01 * * *"
  workflow_dispatch:
  pull_request: # TODO: remove this trigger before merging because for some time the workflow should run only on schedule until the invariant tests are stable enough to be run on every pull request

permissions: read-all

jobs:
  l1-contracts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Install foundryup-zksync
        run: |
          curl -L https://raw.githubusercontent.com/matter-labs/foundry-zksync/nightly-420660c5243e06af1f12febb1765a9abc9c77461/install-foundry-zksync | bash
      
      - name: Install foundry-zksync
        run: |
          foundryup-zksync --install nightly-27360d4c8d12beddbb730dae07ad33a206b38f4b