name: Invariant Tests

on:
  schedule:
    - cron: "00 01 * * *"
  workflow_dispatch:
  pull_request: # TODO: remove this trigger before merging because for some time the workflow should run only on schedule until the invariant tests are stable enough to be run on every pull request

permissions: read-all

jobs:
  l1-contracts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install foundry-zksync
        uses: dutterbutter/foundry-zksync-toolchain@bbc40c8ed7a22d2b16cf7349d2880f811bab3c7e
        with:
          version: nightly-27360d4c8d12beddbb730dae07ad33a206b38f4b
