name: System contracts CI

on:
  pull_request:

jobs:
  build:
    runs-on: matterlabs-ci-runner-ultra-performance

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install foundry-zksync
        run: |
          mkdir ./foundry-zksync
          curl -LO https://github.com/matter-labs/foundry-zksync/releases/download/nightly-5353a10345187933527fbad213d8c4f6500a775c/foundry_nightly_linux_amd64.tar.gz
          tar zxf foundry_nightly_linux_amd64.tar.gz -C ./foundry-zksync
          chmod +x ./foundry-zksync/forge ./foundry-zksync/cast
          echo "$PWD/foundry-zksync" >> $GITHUB_PATH

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.18.0

      - name: Install Yarn
        run: npm install -g yarn

      - name: Build artifacts
        working-directory: system-contracts
        run: |
          yarn install
          yarn build:foundry
          yarn build

      - name: Create cache
        uses: actions/cache/save@v3
        with:
          key: artifacts-system-${{ github.sha }}
          path: |
            system-contracts/zkout
            system-contracts/cache-forge
            system-contracts/bootloader/build
            system-contracts/artifacts-zk
            system-contracts/cache-zk
            system-contracts/typechain
            system-contracts/contracts-preprocessed

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.18.0
          cache: yarn

      - name: Install dependencies
        run: yarn

      - name: Run lint
        run: yarn lint:check

  test-contracts:
    needs: [build, lint]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.18.0
          cache: yarn

      - name: Run anvil-zksync
        uses: dutterbutter/anvil-zksync-action@v1.1.0
        with:
          mode: run
          releaseTag: ccfff38
          protocolVersion: 28

      - name: Install dependencies
        run: yarn

      - name: Restore artifacts cache
        uses: actions/cache/restore@v3
        with:
          fail-on-cache-miss: true
          key: artifacts-system-${{ github.sha }}
          path: |
            system-contracts/zkout
            system-contracts/cache-forge
            system-contracts/bootloader/build
            system-contracts/artifacts-zk
            system-contracts/cache-zk
            system-contracts/typechain
            system-contracts/contracts-preprocessed

      - name: Collect Workflow Telemetry
        uses: catchpoint/workflow-telemetry-action@v2
        with:
          metric_frequency: 5 # Collect metrics every 5 seconds
          proc_trace_chart_show: true # Display process trace chart
          proc_trace_table_show: true # Display process trace table

      - name: Run tests
        timeout-minutes: 60 # Set timeout to 60 minutes
        run: yarn sc test

      - name: Print output logs of era_test_node
        if: always()
        run: cat anvil-zksync.log
